/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        navy: {
          950: '#060B17',
          900: '#0B1329',
          850: '#0F1A36',
          800: '#152449',
          700: '#1E356A',
        },
        brand: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
        },
        "tertiary-fixed": "#dbe1ff",
        "secondary-container": "#708cfd",
        "on-tertiary-fixed": "#00174b",
        "tertiary": "#000000",
        "outline": "#76777d",
        "secondary-fixed": "#dde1ff",
        "on-secondary-fixed": "#001453",
        "background": "#f8f9ff",
        "primary-fixed-dim": "#bec6e0",
        "surface-container-highest": "#d3e4fe",
        "secondary": "#3755c3",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#b8c4ff",
        "on-primary-fixed-variant": "#3f465c",
        "surface": "#f8f9ff",
        "surface-variant": "#d3e4fe",
        "inverse-surface": "#213145",
        "primary": "#000000",
        "on-secondary": "#ffffff",
        "surface-container-high": "#dce9ff",
        "on-secondary-fixed-variant": "#173bab",
        "surface-bright": "#f8f9ff",
        "on-primary-fixed": "#131b2e",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#00217a",
        "on-tertiary-fixed-variant": "#003ea8",
        "on-surface-variant": "#45464d",
        "on-error": "#ffffff",
        "on-background": "#0b1c30",
        "on-primary-container": "#7c839b",
        "surface-container-low": "#eff4ff",
        "outline-variant": "#c6c6cd",
        "surface-tint": "#565e74",
        "surface-dim": "#cbdbf5",
        "tertiary-fixed-dim": "#b4c5ff",
        "inverse-primary": "#bec6e0",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#dae2fd",
        "on-surface": "#0b1c30",
        "tertiary-container": "#00174b",
        "on-tertiary-container": "#497cff",
        "primary-container": "#131b2e",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "inverse-on-surface": "#eaf1ff",
        "surface-container": "#e5eeff"
      },
      fontFamily: {
        sans: ['Manrope', 'Hanken Grotesk', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        'body-sm': ['Hanken Grotesk'],
        'headline-lg': ['Manrope'],
        'headline-sm': ['Manrope'],
        'label-md': ['Hanken Grotesk'],
        'headline-md': ['Manrope'],
        'body-lg': ['Hanken Grotesk'],
        'display-lg': ['Manrope'],
        'body-md': ['Hanken Grotesk'],
        'numeric-metric': ['Manrope'],
        'label-xs': ['Hanken Grotesk']
      },
      fontSize: {
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-sm': ['16px', { lineHeight: '24px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'numeric-metric': ['28px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-xs': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '600' }]
      },
      spacing: {
        'space-lg': '1.5rem',
        'space-sm': '0.75rem',
        'space-xs': '0.5rem',
        'panel-padding': '1.25rem',
        'space-md': '1rem',
        'gutter-desktop': '1.5rem',
        'gutter-mobile': '1rem',
        'space-2xs': '0.25rem',
        'space-2xl': '3rem',
        'space-xl': '2rem'
      }
    },
  },
  plugins: [],
}
